#! /bin/sh

podman machine start 2>/dev/null || echo Podman is already running

rm -rf */target

rm -rf ./weaver/src/test/java/org/wookie/weaver/CarpetResourceContractTest.java
rm -rf ./wookie-tamer/src/test/resources/pacts
rm -rf ./wookie-tamer/src/test/java/org/wookie/tamer/FurResourceContractVerificationTests.java

# Reset the test code and application to its initial state (no tests for colours)
# cp initial-state/CarpetResourceTest.java ./weaver/src/test/java/org/wookie/weaver/
cp initial-state/CarpetResource.java ./weaver/src/main/java/org/wookie/weaver/

# This will only work if the server is up, but is useful
curl -i -X POST http://localhost:8088/recorder/clearall

# Remove quarkus extensions so we can show adding them

#cd wookie-tamer
#quarkus extension remove quarkus-pact-provider
#cd ../weaver
#quarkus extension remove quarkus-pact-consumer
#cd ..

